package com.xceder.CTP.api.market;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u4ea7\u54c1\u62a5\u4ef7\u6c47\u7387<br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Thostmduserapi") 
public class CThostFtdcProductExchRateField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcInstrumentIDType */
	@Array({31}) 
	@Field(0) 
	public Pointer<Byte > ProductID() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcCurrencyIDType */
	@Array({4}) 
	@Field(1) 
	public Pointer<Byte > QuoteCurrencyID() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : TThostFtdcExchangeRateType */
	@Field(2) 
	public double ExchangeRate() {
		return this.io.getDoubleField(this, 2);
	}
	/** C type : TThostFtdcExchangeRateType */
	@Field(2) 
	public CThostFtdcProductExchRateField ExchangeRate(double ExchangeRate) {
		this.io.setDoubleField(this, 2, ExchangeRate);
		return this;
	}
	public CThostFtdcProductExchRateField() {
		super();
	}
	public CThostFtdcProductExchRateField(Pointer pointer) {
		super(pointer);
	}
}
