package com.xceder.CTP.api.market;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u4ea4\u6613\u6240\u516c\u544a<br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Thostmduserapi") 
public class CThostFtdcBulletinField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcExchangeIDType */
	@Array({9}) 
	@Field(0) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcDateType */
	@Array({9}) 
	@Field(1) 
	public Pointer<Byte > TradingDay() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : TThostFtdcBulletinIDType */
	@Field(2) 
	public int BulletinID() {
		return this.io.getIntField(this, 2);
	}
	/** C type : TThostFtdcBulletinIDType */
	@Field(2) 
	public CThostFtdcBulletinField BulletinID(int BulletinID) {
		this.io.setIntField(this, 2, BulletinID);
		return this;
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(3) 
	public int SequenceNo() {
		return this.io.getIntField(this, 3);
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(3) 
	public CThostFtdcBulletinField SequenceNo(int SequenceNo) {
		this.io.setIntField(this, 3, SequenceNo);
		return this;
	}
	/** C type : TThostFtdcNewsTypeType */
	@Array({3}) 
	@Field(4) 
	public Pointer<Byte > NewsType() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : TThostFtdcNewsUrgencyType */
	@Field(5) 
	public byte NewsUrgency() {
		return this.io.getByteField(this, 5);
	}
	/** C type : TThostFtdcNewsUrgencyType */
	@Field(5) 
	public CThostFtdcBulletinField NewsUrgency(byte NewsUrgency) {
		this.io.setByteField(this, 5, NewsUrgency);
		return this;
	}
	/** C type : TThostFtdcTimeType */
	@Array({9}) 
	@Field(6) 
	public Pointer<Byte > SendTime() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : TThostFtdcAbstractType */
	@Array({81}) 
	@Field(7) 
	public Pointer<Byte > Abstract() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : TThostFtdcComeFromType */
	@Array({21}) 
	@Field(8) 
	public Pointer<Byte > ComeFrom() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : TThostFtdcContentType */
	@Array({501}) 
	@Field(9) 
	public Pointer<Byte > Content() {
		return this.io.getPointerField(this, 9);
	}
	/** C type : TThostFtdcURLLinkType */
	@Array({201}) 
	@Field(10) 
	public Pointer<Byte > URLLink() {
		return this.io.getPointerField(this, 10);
	}
	/** C type : TThostFtdcMarketIDType */
	@Array({31}) 
	@Field(11) 
	public Pointer<Byte > MarketID() {
		return this.io.getPointerField(this, 11);
	}
	public CThostFtdcBulletinField() {
		super();
	}
	public CThostFtdcBulletinField(Pointer pointer) {
		super(pointer);
	}
}
