package com.xceder.CTP.api.market;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u5f53\u524d\u671f\u6743\u5408\u7ea6\u6267\u884c\u504f\u79fb\u503c\u7684\u8be6\u7ec6\u5185\u5bb9<br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Thostmduserapi") 
public class CThostFtdcStrikeOffsetField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcInstrumentIDType */
	@Array({31}) 
	@Field(0) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcInvestorRangeType */
	@Field(1) 
	public byte InvestorRange() {
		return this.io.getByteField(this, 1);
	}
	/** C type : TThostFtdcInvestorRangeType */
	@Field(1) 
	public CThostFtdcStrikeOffsetField InvestorRange(byte InvestorRange) {
		this.io.setByteField(this, 1, InvestorRange);
		return this;
	}
	/** C type : TThostFtdcBrokerIDType */
	@Array({11}) 
	@Field(2) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : TThostFtdcInvestorIDType */
	@Array({13}) 
	@Field(3) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : TThostFtdcMoneyType */
	@Field(4) 
	public double Offset() {
		return this.io.getDoubleField(this, 4);
	}
	/** C type : TThostFtdcMoneyType */
	@Field(4) 
	public CThostFtdcStrikeOffsetField Offset(double Offset) {
		this.io.setDoubleField(this, 4, Offset);
		return this;
	}
	/** C type : TThostFtdcStrikeOffsetTypeType */
	@Field(5) 
	public byte OffsetType() {
		return this.io.getByteField(this, 5);
	}
	/** C type : TThostFtdcStrikeOffsetTypeType */
	@Field(5) 
	public CThostFtdcStrikeOffsetField OffsetType(byte OffsetType) {
		this.io.setByteField(this, 5, OffsetType);
		return this;
	}
	public CThostFtdcStrikeOffsetField() {
		super();
	}
	public CThostFtdcStrikeOffsetField(Pointer pointer) {
		super(pointer);
	}
}
