package com.xceder.CTP.api.trade;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u8f93\u5165\u6279\u91cf\u62a5\u5355\u64cd\u4f5c<br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Thosttraderapi") 
public class CThostFtdcInputBatchOrderActionField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcBrokerIDType */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcInvestorIDType */
	@Array({13}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : TThostFtdcOrderActionRefType */
	@Field(2) 
	public int OrderActionRef() {
		return this.io.getIntField(this, 2);
	}
	/** C type : TThostFtdcOrderActionRefType */
	@Field(2) 
	public CThostFtdcInputBatchOrderActionField OrderActionRef(int OrderActionRef) {
		this.io.setIntField(this, 2, OrderActionRef);
		return this;
	}
	/** C type : TThostFtdcRequestIDType */
	@Field(3) 
	public int RequestID() {
		return this.io.getIntField(this, 3);
	}
	/** C type : TThostFtdcRequestIDType */
	@Field(3) 
	public CThostFtdcInputBatchOrderActionField RequestID(int RequestID) {
		this.io.setIntField(this, 3, RequestID);
		return this;
	}
	/** C type : TThostFtdcFrontIDType */
	@Field(4) 
	public int FrontID() {
		return this.io.getIntField(this, 4);
	}
	/** C type : TThostFtdcFrontIDType */
	@Field(4) 
	public CThostFtdcInputBatchOrderActionField FrontID(int FrontID) {
		this.io.setIntField(this, 4, FrontID);
		return this;
	}
	/** C type : TThostFtdcSessionIDType */
	@Field(5) 
	public int SessionID() {
		return this.io.getIntField(this, 5);
	}
	/** C type : TThostFtdcSessionIDType */
	@Field(5) 
	public CThostFtdcInputBatchOrderActionField SessionID(int SessionID) {
		this.io.setIntField(this, 5, SessionID);
		return this;
	}
	/** C type : TThostFtdcExchangeIDType */
	@Array({9}) 
	@Field(6) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : TThostFtdcUserIDType */
	@Array({16}) 
	@Field(7) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : TThostFtdcInvestUnitIDType */
	@Array({17}) 
	@Field(8) 
	public Pointer<Byte > InvestUnitID() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : TThostFtdcIPAddressType */
	@Array({16}) 
	@Field(9) 
	public Pointer<Byte > IPAddress() {
		return this.io.getPointerField(this, 9);
	}
	/** C type : TThostFtdcMacAddressType */
	@Array({21}) 
	@Field(10) 
	public Pointer<Byte > MacAddress() {
		return this.io.getPointerField(this, 10);
	}
	public CThostFtdcInputBatchOrderActionField() {
		super();
	}
	public CThostFtdcInputBatchOrderActionField(Pointer pointer) {
		super(pointer);
	}
}
