package com.xceder.CTP.api.trade;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u4fe1\u606f\u5206\u53d1<br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Thosttraderapi") 
public class CThostFtdcDisseminationField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcSequenceSeriesType */
	@Field(0) 
	public short SequenceSeries() {
		return this.io.getShortField(this, 0);
	}
	/** C type : TThostFtdcSequenceSeriesType */
	@Field(0) 
	public CThostFtdcDisseminationField SequenceSeries(short SequenceSeries) {
		this.io.setShortField(this, 0, SequenceSeries);
		return this;
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(1) 
	public int SequenceNo() {
		return this.io.getIntField(this, 1);
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(1) 
	public CThostFtdcDisseminationField SequenceNo(int SequenceNo) {
		this.io.setIntField(this, 1, SequenceNo);
		return this;
	}
	public CThostFtdcDisseminationField() {
		super();
	}
	public CThostFtdcDisseminationField(Pointer pointer) {
		super(pointer);
	}
}
