package com.xceder.CTP.api.trade;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u8f93\u5165\u7684\u6267\u884c\u5ba3\u544a<br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Thosttraderapi") 
public class CThostFtdcInputExecOrderField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcBrokerIDType */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcInvestorIDType */
	@Array({13}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : TThostFtdcInstrumentIDType */
	@Array({31}) 
	@Field(2) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : TThostFtdcOrderRefType */
	@Array({13}) 
	@Field(3) 
	public Pointer<Byte > ExecOrderRef() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : TThostFtdcUserIDType */
	@Array({16}) 
	@Field(4) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : TThostFtdcVolumeType */
	@Field(5) 
	public int Volume() {
		return this.io.getIntField(this, 5);
	}
	/** C type : TThostFtdcVolumeType */
	@Field(5) 
	public CThostFtdcInputExecOrderField Volume(int Volume) {
		this.io.setIntField(this, 5, Volume);
		return this;
	}
	/** C type : TThostFtdcRequestIDType */
	@Field(6) 
	public int RequestID() {
		return this.io.getIntField(this, 6);
	}
	/** C type : TThostFtdcRequestIDType */
	@Field(6) 
	public CThostFtdcInputExecOrderField RequestID(int RequestID) {
		this.io.setIntField(this, 6, RequestID);
		return this;
	}
	/** C type : TThostFtdcBusinessUnitType */
	@Array({21}) 
	@Field(7) 
	public Pointer<Byte > BusinessUnit() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : TThostFtdcOffsetFlagType */
	@Field(8) 
	public byte OffsetFlag() {
		return this.io.getByteField(this, 8);
	}
	/** C type : TThostFtdcOffsetFlagType */
	@Field(8) 
	public CThostFtdcInputExecOrderField OffsetFlag(byte OffsetFlag) {
		this.io.setByteField(this, 8, OffsetFlag);
		return this;
	}
	/** C type : TThostFtdcHedgeFlagType */
	@Field(9) 
	public byte HedgeFlag() {
		return this.io.getByteField(this, 9);
	}
	/** C type : TThostFtdcHedgeFlagType */
	@Field(9) 
	public CThostFtdcInputExecOrderField HedgeFlag(byte HedgeFlag) {
		this.io.setByteField(this, 9, HedgeFlag);
		return this;
	}
	/** C type : TThostFtdcActionTypeType */
	@Field(10) 
	public byte ActionType() {
		return this.io.getByteField(this, 10);
	}
	/** C type : TThostFtdcActionTypeType */
	@Field(10) 
	public CThostFtdcInputExecOrderField ActionType(byte ActionType) {
		this.io.setByteField(this, 10, ActionType);
		return this;
	}
	/** C type : TThostFtdcPosiDirectionType */
	@Field(11) 
	public byte PosiDirection() {
		return this.io.getByteField(this, 11);
	}
	/** C type : TThostFtdcPosiDirectionType */
	@Field(11) 
	public CThostFtdcInputExecOrderField PosiDirection(byte PosiDirection) {
		this.io.setByteField(this, 11, PosiDirection);
		return this;
	}
	/** C type : TThostFtdcExecOrderPositionFlagType */
	@Field(12) 
	public byte ReservePositionFlag() {
		return this.io.getByteField(this, 12);
	}
	/** C type : TThostFtdcExecOrderPositionFlagType */
	@Field(12) 
	public CThostFtdcInputExecOrderField ReservePositionFlag(byte ReservePositionFlag) {
		this.io.setByteField(this, 12, ReservePositionFlag);
		return this;
	}
	/** C type : TThostFtdcExecOrderCloseFlagType */
	@Field(13) 
	public byte CloseFlag() {
		return this.io.getByteField(this, 13);
	}
	/** C type : TThostFtdcExecOrderCloseFlagType */
	@Field(13) 
	public CThostFtdcInputExecOrderField CloseFlag(byte CloseFlag) {
		this.io.setByteField(this, 13, CloseFlag);
		return this;
	}
	/** C type : TThostFtdcExchangeIDType */
	@Array({9}) 
	@Field(14) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 14);
	}
	/** C type : TThostFtdcInvestUnitIDType */
	@Array({17}) 
	@Field(15) 
	public Pointer<Byte > InvestUnitID() {
		return this.io.getPointerField(this, 15);
	}
	/** C type : TThostFtdcAccountIDType */
	@Array({13}) 
	@Field(16) 
	public Pointer<Byte > AccountID() {
		return this.io.getPointerField(this, 16);
	}
	/** C type : TThostFtdcCurrencyIDType */
	@Array({4}) 
	@Field(17) 
	public Pointer<Byte > CurrencyID() {
		return this.io.getPointerField(this, 17);
	}
	/** C type : TThostFtdcClientIDType */
	@Array({11}) 
	@Field(18) 
	public Pointer<Byte > ClientID() {
		return this.io.getPointerField(this, 18);
	}
	/** C type : TThostFtdcIPAddressType */
	@Array({16}) 
	@Field(19) 
	public Pointer<Byte > IPAddress() {
		return this.io.getPointerField(this, 19);
	}
	/** C type : TThostFtdcMacAddressType */
	@Array({21}) 
	@Field(20) 
	public Pointer<Byte > MacAddress() {
		return this.io.getPointerField(this, 20);
	}
	public CThostFtdcInputExecOrderField() {
		super();
	}
	public CThostFtdcInputExecOrderField(Pointer pointer) {
		super(pointer);
	}
}
